#!/bin/bash

set -e

if [ $# -ne 1 ] ; then
	echo "Usage: $0 <release>"
	exit 1
fi
version=$1

if [ -z "${TUF_TARGETS_PASSPHRASE}" ] ; then
	read -sp "Enter your targets key password:" TUF_TARGETS_PASSPHRASE
	echo ""
fi
if [ -z "${TUF_SNAPSHOT_PASSPHRASE}" ] ; then
	read -sp "Enter your snapshot key password:" TUF_SNAPSHOT_PASSPHRASE
	echo ""
fi
if [ -z "${TUF_TIMESTAMP_PASSPHRASE}" ] ; then
	read -sp "Enter your timestamp key password:" TUF_TIMESTAMP_PASSPHRASE
	echo ""
fi

export TUF_TARGETS_PASSPHRASE TUF_SNAPSHOT_PASSPHRASE TUF_TIMESTAMP_PASSPHRASE

URLBASE="https://github.com/foundriesio/fioctl/releases/download/${version}"
PLATFORMS="
	darwin/amd64
	darwin/arm64
	linux/amd64
	linux/arm64
	windows/amd64
"
for p in $PLATFORMS ; do
	artifact="fioctl-$(echo $p | sed 's/\//-/g')"
	if [ "${p}" = "windows/amd64" ] ; then
		artifact="${artifact}.exe"
	fi

	url="${URLBASE}/${artifact}"
	custom="{\"platform\": \"$p\", \"version\": \"$version\", \"uri\": \"$url\"}"

	echo "= Downloading ${url}"
	wget -O staged/targets/${artifact}_${version} ${url}

	./bin/tuf add --expires=180 --custom "${custom}" "${artifact}_${version}"
done

echo "updating snapshots"
./bin/tuf snapshot --expires=180
echo "updating timestamps"
./bin/tuf timestamp --expires=7
echo "updating ./repostory"
./bin/tuf commit

echo "now check changes in ./repository and then commit and push"
