# Build using golang container
FROM golang:1.21.0-alpine3.17

RUN apk add --update --no-cache \
    git \
    g++ \ 
    make

RUN mkdir -p $HOME/fioctl
WORKDIR $HOME/fioctl

COPY . .
RUN go mod download
